version: '3.8'

services:
  pingserver:
    deploy:
      resources:
        limits:
          cpus: "2"
    build:
      context: ./pingserver
      dockerfile: Dockerfile
    image: lies-pingserver
    ports:
      - "8080:8080"

  beyla:
    image: grafana/beyla:0.1.0
    privileged: true # in some environments (not GH Pull Requests) you can set it to false and then cap_add: [ SYS_ADMIN ]
    pid: "service:pingserver"
    environment:
#      PRINT_TRACES: "true"
      OPEN_PORT: 8080
      METRICS_REPORT_TARGET: true
      METRICS_INTERVAL: "1s"
      BPF_BATCH_TIMEOUT: "1s"
      BEYLA_PROMETHEUS_PORT: 8999
    ports:
      - "8999:8999"

  # Prometheus
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    container_name: prometheus
    command:
      - --storage.tsdb.retention.time=1m
      - --config.file=/etc/prometheus/prometheus-config.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
    volumes:
      - ./configs/:/etc/prometheus
    ports:
      - "9090:9090"

  wrk:
    deploy:
      resources:
        reservations:
          cpus: "4.0"
    image: elswork/wrk
    command: ["-t4", "-c60", "-d20s", "-t60", "--latency", "http://pingserver:8080/ping"]
    depends_on:
      pingserver:
        condition: service_started
