global:
  evaluation_interval: 1s
  scrape_interval: 1s
scrape_configs:
  - job_name: beyla
    honor_labels: true
    static_configs:
      - targets:
          - 'beyla:8999'
  - job_name: pingserver
    static_configs:
      - targets:
          - 'pingserver:8080'
